### ISSUE TITLE
Question About the computation of correctness label

### ISSUE THREAD

**Issue by zhangmingjie2002** [launchnlp/LitCab#3]
Hello , I have read your relevant paper , and try to reproduce the project.The new idea you propose is really interesting and i fully appreciate your talent! But i have got some trouble here: when it comes to the computation of ECE , I recognize that we should know acc(bi) and conf(bi), which i guess are possibility score and correctness label respectively.But how can i get the correctness label according to GPT-4  as is depicted in your paper? I guess you have fulfilled it in your code but with limited insturction i cannot get the point. So, i look forward to your responce and i hope you can give me a more explicit insturction ,thank you!

**Comment by zhangmingjie2002** [comment]
according to line 34 in get_ece_for_long_form.py , maybe you refer (bins[bin_idx] + bins[bin_idx+1])/2 to conf(bi) ,which is so weird to me.

**Comment by zhangmingjie2002** [comment]
Let me mend my question to be less confusing. How can i get the correctness label of generation? You mention reference at phase level(how can i get the reference) and gpt-4 to determine answer at paragraph level(how do you achieve it in your code)

**Comment by zhangmingjie2002** [comment]
amazing, a disappointing project with no achievement of Litcab and model training and a lot of miss of dataset(such as how to differentiate true answer generated in paragraph level and where is your dataset of bioGen). Interesting, how dare you forward your paper with a github link like this. Waiting for rebutter please!

**Comment by XinLiu-cs** [comment]
Let me address your concerns as follows:

1. **Correctness Label of Generation:** For phrase-level accuracy, the reference is provided in the test set, located in` test.txt`. For paragraph-level, I have provided a script `src/get_gpt_correctness.py` that uses GPT-4 to determine correctness labels. This is mentioned in the instructions. Please refer to that for more details.

3. **Confidence Calculation:** The expression (bins[bin_idx] + bins[bin_idx+1])/2 is used to calculate conf(bi).

5. **BioGen Dataset:** For long-form generation tasks, only the demonstration and entities are required, as explicit references are not needed to evaluate the model’s generation. Demonstrations can be found in `name_bio/demos.txt`, and the list of entities is in `name_bio/prompt_entities.txt`.

6. **Model Training:** I plan to upload this part by the end of the month. Please stay tuned.

7. **Communication:** If I do not respond in a timely manner, please send a reminder to liuxincs@umich.edu. I do not regularly check the issue page.

**Comment by XinLiu-cs** [comment]
questions are through via emails
